### ISSUE TITLE
Update Sponsorenliste

### ISSUE THREAD

**Issue by jtridev** [jtridev/jtriweb#1]

**Comment by siziegler** [comment]
Swisslos und Schwyzer Sportverband (Schwyzer Sport - www.schwyzersport.ch) muss unbedingt auf Sponsorenliste

**Comment by siziegler** [comment]
Hier ist das Logo sowie Anleitung für die Verwendung:

https://www.sz.ch/privatpersonen/bildung-schulen-sport/sport/swisslos.html/72-512-468-465-4915
