### ISSUE TITLE
Meta Information mit sinnvollem Inhalt

### ISSUE THREAD

**Issue by Walibu** [jtridev/jtriweb#11]
Über Google findet man uns fast nicht. Habe jetzt festgestellt, dass wenn man einen Link z.B. in Whatsapp einfügt, dann Default Meta-Information über Joomla,... drinn stehen.

Man sollte unbedingt, sinnvolle Schlüsselwörter und Beschreibungen vom Jtri einfügen, und den DefaultEintrag Joomla entfernen. Momentan steht:
<meta name="keywords" content="joomla, Joomla" />
<meta name="description" content="Joomla! - the dynamic portal engine and content management system" />

Sinnvolle Keywords: Jtri, Joggerträff Triathlonclub, Triathlon, Schwimmen, Velo, Laufen, Polysportiv, Pfäffikon, Region Obersee, Pfäffikon SZ, Rapperswil, Jtri Jugend, Jtri Kids, Jugendtraining Uznach, Ironman 70.3 Rapperswil

Beschreibung könnte man einen Auszug oder zusammengefasst den Text von http://jtri.ch/index.php/callisto/ueber-uns   einfügen.

**Comment by jtridev** [comment]
Danke Walti, habe ich dementsprechend angepasst.
