### ISSUE TITLE
Neue Fotos für Image Rotator auf Startseite

### ISSUE THREAD

**Issue by siziegler** [jtridev/jtriweb#4]
Hier müssen wir zuerst ein paar Fotos mit den neuen Tenüs machen

**Comment by Walibu** [comment]
Als Triathlonclub, sollte mindestens 1 Bild einen Jtri während Triathlon Wettkampf zeigen:)

**Comment by jtridev** [comment]
Werde am 70.3 in Rappi mit meiner Kamera anwesend sein und hoffentlich viele gute Bilder machen können.

**Comment by Walibu** [comment]
Danke, Beim Ironkids gibts leider nur noch laufen, ist noch nicht klar wer von Jungen mitmacht.
Mach am Sonntag auch Fotos beim Verpflegungsstand, km4, die Helfer haben es auch verdient und gehört auch zur Klub arbeit!
